language: php

sudo: false

cache:
    directories:
        - $HOME/.composer/cache

php:
    - 5.6
    - 7.0

branches:
  only:
  - /^dev-.*$/
  - phpunit-support

before_install:
    - travis_retry composer self-update

install:
    - travis_retry composer update ${COMPOSER_FLAGS} --prefer-source --no-interaction

script:
    - composer test-ci